//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConwaysGameOfLife.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConwaysGameOfLife.Resources.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be sent to main menu ater 5 seconds..
        /// </summary>
        internal static string BackToMainMenuMessage {
            get {
                return ResourceManager.GetString("BackToMainMenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 8 games can be shown on the screen.
        ///How many games you want to see on the screen?.
        /// </summary>
        internal static string ChooseMultipleGamesMessage {
            get {
                return ResourceManager.GetString("ChooseMultipleGamesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many games you want to play?
        ///Input number from 2 to 1000..
        /// </summary>
        internal static string GameCountInputMessage {
            get {
                return ResourceManager.GetString("GameCountInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is over!.
        /// </summary>
        internal static string GameIsOverMessage {
            get {
                return ResourceManager.GetString("GameIsOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to stop game and go back to main menu..
        /// </summary>
        internal static string GoBackMessage {
            get {
                return ResourceManager.GetString("GoBackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one of the games from the list.
        ///List of saved games:.
        /// </summary>
        internal static string ListOfSavedGamesIntro {
            get {
                return ResourceManager.GetString("ListOfSavedGamesIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live cells: .
        /// </summary>
        internal static string LiveCellsMessage {
            get {
                return ResourceManager.GetString("LiveCellsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ██████╗  █████╗ ███╗   ███╗███████╗     ██████╗ ███████╗    ██╗     ██╗███████╗███████╗
        ///██╔════╝ ██╔══██╗████╗ ████║██╔════╝    ██╔═══██╗██╔════╝    ██║     ██║██╔════╝██╔════╝
        ///██║  ███╗███████║██╔████╔██║█████╗      ██║   ██║█████╗      ██║     ██║█████╗  █████╗  
        ///██║   ██║██╔══██║██║╚██╔╝██║██╔══╝      ██║   ██║██╔══╝      ██║     ██║██╔══╝  ██╔══╝  
        ///╚██████╔╝██║  ██║██║ ╚═╝ ██║███████╗    ╚██████╔╝██║         ███████╗██║██║     ███████╗
        ///╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝     ╚═════╝ ╚═╝         ╚═ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainMenuIntro {
            get {
                return ResourceManager.GetString("MainMenuIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose if you want EXIT game ang go back to main menu. Or CONTINUE and choose different cells to display on a screen..
        /// </summary>
        internal static string MenuOnStopIntro {
            get {
                return ResourceManager.GetString("MenuOnStopIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have saved games! You will be sent back to main menu..
        /// </summary>
        internal static string MessageForEmptyGamesList {
            get {
                return ResourceManager.GetString("MessageForEmptyGamesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Remember that MAX Height is 15 and MAX Width is 20..
        /// </summary>
        internal static string MessageForMultipleGamesFieldSize {
            get {
                return ResourceManager.GetString("MessageForMultipleGamesFieldSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Remember that MAX Height is 30 and MAX Width is 60..
        /// </summary>
        internal static string MessageForOneGameFieldSize {
            get {
                return ResourceManager.GetString("MessageForOneGameFieldSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press SPACE to stop the game. If you want to save or change displayed grids..
        /// </summary>
        internal static string MessageToStopForMultipleGames {
            get {
                return ResourceManager.GetString("MessageToStopForMultipleGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input NUMBER of the game you want to restore..
        /// </summary>
        internal static string RuleForRestoringGame {
            get {
                return ResourceManager.GetString("RuleForRestoringGame", resourceCulture);
            }
        }
    }
}
